# File contains parameters for controlling encoder models and training process
# To define optimization, go to optimizer.py

train_data_ratio: 0.9
batch_size: 32
num_epochs: 5
device: cuda

eeg_encoder:
  input_length: 525
  num_channels: 63
  output_dim: 512