wandb_api_key:  # change it for your own at https://wandb.ai/settings#api

experiment_name: Sole EEG contrastive
output_dir: 

img_latent_train_path: data/ViT-H-14_features_train.pt
img_latent_test_path: data/ViT-H-14_features_test.pt
subs_dir_path: data/Preprocessed_data_250Hz

max_epochs: 3
accelerator: "gpu"
num_devices: 1
batch_size: 40

num_subjects: 5

eeg_kwargs:
    input_length: 250
    num_channels: 63
    output_dim: 1024 # = fmri_kwargs.embed_dim = fuser_kwargs.emb_dim
    conv_output_dim: 1440    # should be calculated manually
    conv_kernal_size: 50    # no impact
    transformer_num_layers: 10
    transformer_dim_feedforward: 1024
    transformer_nhead: 5
    transformer_dropout: 0.1
    transformer_activation: relu

init_logit_scale: 1.0

optimizer_kwargs:
    lr: 1e-4
    betas:
        - 0.9
        - 0.999
    weight_decay: 1e-5

scheduler_kwargs:
    