wandb_api_key: ec40053455ec5c12dea7d32134b9a23ac16f062e # change it for your own at https://wandb.ai/settings#api
experiment_name: Simultaneous fMRI-EEG
output_dir: /home/jovyan/shares/SR004.nfs2/nkiselev/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/train/improved-dataloader
log_with: wandb
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
mixed_precision: bf16
max_train_epochs: 100000
max_train_steps: 100000
checkpointing_steps: 1000

model_kwargs:

    ridge_kwargs:
        masks_path: /home/jovyan/shares/SR004.nfs2/nkiselev/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/natview/fmri_masks
        out_dim: 4096 # = fmri_kwargs.latent_dim

    fmri_kwargs:
        latent_dim: 4096 # = ridge_kwargs.out_dim
        patch_size: 16
        embed_dim: 1024 # = eeg_kwargs.output_dim = fuser_kwargs.emb_dim
        in_chans: 1
        depth: 12
        num_heads: 8
        mlp_ratio: 4
        dropout: 0.1

    eeg_kwargs:
        input_length: 525
        num_channels: 61
        output_dim: 1024 # = fmri_kwargs.embed_dim = fuser_kwargs.emb_dim
        conv_output_dim: 1820
        conv_kernal_size: 50
        transformer_num_layers: 1
        transformer_dim_feedforward: 256
        transformer_nhead: 4
        transformer_dropout: 0.25
        transformer_activation: gelu
        
    fuser_kwargs:
        fuser_name: weight # or mlp, and then emb_dim is required
        emb_dim: 1024 # = fmri_kwargs.embed_dim = eeg_kwargs.output_dim

dataloader_kwargs:
    dataset:
        json_path: /home/jovyan/shares/SR004.nfs2/nkiselev/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/dataset.json
        recovery_mode: kNN_weighted
    dataloader:
        batch_size: 8

optimizer_kwargs:
    lr: 3e-4
    betas:
        - 0.9
        - 0.999
    weight_decay: 1e-5

scheduler_kwargs:
    name: constant
    warmup_steps: 1000