output_dir: "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/train_updated/checkpoints/flow-matching-prior-fmri-monkeys-44000"
device: "cuda:0"
resume_from_checkpoint: latest
mixed_precision: bf16
num_training_steps: 10000
checkpointing_steps: 1000
max_norm: 1.0
scheduler_scale: 1.0

model_kwargs:
    latent_dim: 1024  # = CLIP-ViT-H-14 image embedding dim 
    time_dim: 512
    model_dim: 2048
    ff_dim: 5120
    num_blocks: 12

dataloader_kwargs:
    dataset:
        json_path: "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/dataset.json"
        combined_dir: "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/combined/fmri-monkeys-44000"
    dataloader:
        batch_size: 32
        shuffle: True
        num_workers: 0
        pin_memory: False

optimizer_kwargs:
    lr: 1.0e-05
    betas:
        - 0.9
        - 0.95
    weight_decay: 0.0

scheduler_kwargs:
    name: constant_with_warmup
    warmup_steps: 100