# Logging
log_with: "tensorboard"
tensorboard_log_dir: "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/train_updated/logs"
device: "cuda:0"

# Experiment settings
experiment_name: "Simultaneous_fMRI-EEG"
output_dir: "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/train_updated/checkpoints/fmri-monkeys"

# Training settings
resume_from_checkpoint: "latest"
gradient_accumulation_steps: 1
mixed_precision: "bf16"
max_train_epochs: 100000
max_train_steps: 100000
checkpointing_steps: 1000

# Model settings
mode: "fmri"
model_kwargs:

    ridge_kwargs:
        masks_path: /home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/natview/data/fmri_masks
        out_dim: 4096 # = fmri_kwargs.latent_dim

    fmri_kwargs:
        latent_dim: 4096 # = ridge_kwargs.out_dim
        patch_size: 16
        embed_dim: 1024 # = eeg_kwargs.output_dim = fuser_kwargs.emb_dim
        in_chans: 1
        depth: 24
        num_heads: 16
        mlp_ratio: 4
        dropout: 0.0

# Data settings
dataloader_kwargs:
    dataset:
        json_path: "/home/jovyan/shares/SR008.fs2/nkiselev/sandbox/visual_stimuli_reconstruction/CreationOfIntelligentSystems_Simultaneous_fMRI-EEG/code/data/dataset.json"
        featured_videos: 
            - monkey1
            - monkey2
            - monkey5
            # - dme
            # - inscapes
    dataloader:
        batch_size: 8

# Optimization settings
optimizer_kwargs:
  lr: 3e-4
  betas: [0.9, 0.999]
  weight_decay: 1e-5

# Scheduler settings
scheduler_kwargs:
  name: "constant"
  warmup_steps: 1000